// El dominio/contrato OpenAPI habla en inglés (ALLY, ACTIVE, PENDING); el esquema
// de Postgres heredado del flujo Flutter/handle_new_user usa español (ALIADO,
// ACTIVO, PENDIENTE). Esta es la única frontera de traducción entre ambos.
const ROL_TO_DB = { ALLY: 'ALIADO', CLIENT: 'CLIENTE', ADMIN: 'ADMIN' };
const ESTADO_USUARIO_TO_DB = { ACTIVE: 'ACTIVO', INACTIVE: 'INACTIVO' };
const ESTADO_VERIFICACION_TO_DB = { PENDING: 'PENDIENTE', VERIFIED: 'VERIFICADO', REJECTED: 'RECHAZADO' };

const ROL_FROM_DB = { ALIADO: 'ALLY', CLIENTE: 'CLIENT', ADMIN_TENANT: 'ADMIN', ADMIN: 'ADMIN' };
const ESTADO_USUARIO_FROM_DB = { ACTIVO: 'ACTIVE', INACTIVO: 'INACTIVE' };
const ESTADO_VERIFICACION_FROM_DB = { PENDIENTE: 'PENDING', VERIFICADO: 'VERIFIED', RECHAZADO: 'REJECTED' };

module.exports = {
  ROL_TO_DB,
  ESTADO_USUARIO_TO_DB,
  ESTADO_VERIFICACION_TO_DB,
  ROL_FROM_DB,
  ESTADO_USUARIO_FROM_DB,
  ESTADO_VERIFICACION_FROM_DB,
};
